### ISSUE TITLE
Update artifact paths in buildspec.yml

### ISSUE THREAD

**Issue by stephanielingwood** [mandusm/aws-modernization-workshop#135]
It is currently: 

```yml
artifacts:
  files:
  - '*/imagedefinitions.json'
  base-directory: ${CODEBUILD_SRC_DIR}
```

Need to remove the `base-directory` and the `*/` in the file path.
